[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  contact = "contact"

[[forms.contact.notifications]]
  provider = "email"
  to = "contact@aethertechnologies.se"
  from = "noreply@netlify.com"
  subject = "New Contact Form Submission"
  includeData = true
