[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms.contact]
    [forms.contact.notifications]
      [forms.contact.notifications.email]
        to = "contact@aethertechnologies.se"
